package goroutine

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// TestPhase14GoroutineBridgeSentinel is the MEP-74 phase 14
// end-to-end sentinel. It writes the generated runtime file
// plus a representative channel-shim and callback-shim into a
// scratch wrapper package and asserts that the whole thing
// compiles cleanly via `go build` with the `mochi_wrap` build
// tag (no cgo needed because the generated file uses only
// runtime/cgo, which is a regular Go stdlib package).
//
// The sentinel also asserts that the rendered runtime + the
// rendered shims are byte-deterministic (so the wrapper-sha256
// lockfile pin under phase 10 is stable across rebuilds).
func TestPhase14GoroutineBridgeSentinel(t *testing.T) {
	if _, err := exec.LookPath("go"); err != nil {
		t.Skipf("go not available: %v", err)
	}

	root := t.TempDir()
	pkgDir := filepath.Join(root, "gowrap_demo")
	if err := os.MkdirAll(pkgDir, 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}

	// Render the runtime, a channel shim, and a callback shim.
	runtimeSrc := RenderRuntime("gowrap_demo")
	chanSrc, err := RenderChannelShim(ChannelShim{
		ModuleFlatName: "demo",
		ElemGoType:     "int64",
		ElemCType:      "int64_t",
		SymbolBase:     "Counter",
		BufferSize:     4,
	})
	if err != nil {
		t.Fatalf("RenderChannelShim: %v", err)
	}
	cbSrc, err := RenderCallbackShim(CallbackShim{
		ModuleFlatName: "demo",
		SymbolBase:     "OnTick",
		Signature:      "func(int64) bool",
	})
	if err != nil {
		t.Fatalf("RenderCallbackShim: %v", err)
	}

	// The shims share the build tag and package clause with the
	// runtime file so they compile in the same translation unit.
	shimFile := fmt.Sprintf("//go:build mochi_wrap\n\n// Code generated by mochi MEP-74 phase 14. DO NOT EDIT.\n\npackage gowrap_demo\n\n%s\n%s", chanSrc, cbSrc)

	if err := os.WriteFile(filepath.Join(pkgDir, "mochi_rt.go"), []byte(runtimeSrc), 0o644); err != nil {
		t.Fatalf("write mochi_rt.go: %v", err)
	}
	if err := os.WriteFile(filepath.Join(pkgDir, "shims.go"), []byte(shimFile), 0o644); err != nil {
		t.Fatalf("write shims.go: %v", err)
	}

	// A go.mod for the scratch package so `go build` does not
	// reach upward and pick up the outer module's go.mod.
	goMod := "module example.com/mochi/gowrap_demo\n\ngo 1.21\n"
	if err := os.WriteFile(filepath.Join(pkgDir, "go.mod"), []byte(goMod), 0o644); err != nil {
		t.Fatalf("write go.mod: %v", err)
	}

	// Compile with the mochi_wrap tag. The runtime + shim files
	// only compile under that tag (their //go:build line scopes
	// them). Without the tag the package would be empty.
	out, err := goBuild(pkgDir, "go", "build", "-tags", "mochi_wrap", "./...")
	if err != nil {
		t.Fatalf("go build failed: %v\n%s", err, out)
	}

	// Without the tag, the build should still succeed -- an
	// empty package is legal -- so we test that too.
	out, err = goBuild(pkgDir, "go", "build", "./...")
	if err != nil {
		t.Fatalf("go build (no tag) failed: %v\n%s", err, out)
	}

	// Deterministic-render assertion: render the runtime ten
	// times and check the sha256 is constant. The wrapper-sha256
	// pin under phase 10 depends on this invariant.
	wantSum := sha256.Sum256([]byte(runtimeSrc))
	for i := 0; i < 10; i++ {
		got := sha256.Sum256([]byte(RenderRuntime("gowrap_demo")))
		if got != wantSum {
			t.Errorf("RenderRuntime drift on iteration %d:\nwant %s\ngot  %s",
				i, hex.EncodeToString(wantSum[:]), hex.EncodeToString(got[:]))
		}
	}

	// Same determinism check for the channel shim.
	chanSum := sha256.Sum256([]byte(chanSrc))
	for i := 0; i < 10; i++ {
		again, err := RenderChannelShim(ChannelShim{
			ModuleFlatName: "demo",
			ElemGoType:     "int64",
			ElemCType:      "int64_t",
			SymbolBase:     "Counter",
			BufferSize:     4,
		})
		if err != nil {
			t.Fatalf("re-render channel shim: %v", err)
		}
		got := sha256.Sum256([]byte(again))
		if got != chanSum {
			t.Errorf("RenderChannelShim drift on iteration %d", i)
		}
	}

	// And the callback shim.
	cbSum := sha256.Sum256([]byte(cbSrc))
	for i := 0; i < 10; i++ {
		again, err := RenderCallbackShim(CallbackShim{
			ModuleFlatName: "demo",
			SymbolBase:     "OnTick",
			Signature:      "func(int64) bool",
		})
		if err != nil {
			t.Fatalf("re-render callback shim: %v", err)
		}
		got := sha256.Sum256([]byte(again))
		if got != cbSum {
			t.Errorf("RenderCallbackShim drift on iteration %d", i)
		}
	}

	// The runtime source must include exactly the four mochi*
	// helpers (no extra symbols that would surprise downstream
	// wrappers).
	for _, want := range []string{
		"mochiAcquireHandle",
		"mochiResolveHandle",
		"mochiReleaseHandle",
	} {
		if strings.Count(runtimeSrc, "func "+want) != 1 {
			t.Errorf("runtime should declare exactly one %s; got %d",
				want, strings.Count(runtimeSrc, "func "+want))
		}
	}
}

// TestPhase14HandlePoolRoundTripIntegration is a runtime-side
// integration check: spawn a goroutine, send a value into a
// channel via the handle pool, recv it on the other end, and
// release the handle. Mirrors the cross-boundary flow without
// touching the cgo c-archive build (so it runs under plain
// `go test`).
func TestPhase14HandlePoolRoundTripIntegration(t *testing.T) {
	p := NewHandlePool(0)
	ch := make(chan int64, 1)
	id, err := p.Acquire(ch)
	if err != nil {
		t.Fatalf("Acquire: %v", err)
	}

	// Producer side (would be the "cgo C side" in production):
	// resolves the handle and sends.
	v, ok := p.Resolve(id)
	if !ok {
		t.Fatalf("Resolve: missed live handle")
	}
	producer := v.(chan int64)

	done := make(chan struct{})
	go func() {
		producer <- 42
		close(done)
	}()

	// Consumer side resolves the same handle and receives.
	v, ok = p.Resolve(id)
	if !ok {
		t.Fatalf("Resolve (consumer): missed live handle")
	}
	consumer := v.(chan int64)
	got := <-consumer
	if got != 42 {
		t.Errorf("got %d; want 42", got)
	}
	<-done

	if !p.Release(id) {
		t.Errorf("Release should succeed")
	}
	if p.Live() != 0 {
		t.Errorf("Live() = %d; want 0 after Release", p.Live())
	}
}

func goBuild(dir, name string, args ...string) (string, error) {
	cmd := exec.Command(name, args...)
	cmd.Dir = dir
	gocache, _ := os.MkdirTemp("", "gocache-")
	gomodcache, _ := os.MkdirTemp("", "gomodcache-")
	defer os.RemoveAll(gocache)
	defer os.RemoveAll(gomodcache)
	cmd.Env = append(os.Environ(),
		"GOCACHE="+gocache,
		"GOMODCACHE="+gomodcache,
		"GOFLAGS=",
		"GO111MODULE=on",
	)
	out, err := cmd.CombinedOutput()
	return string(out), err
}
